#user nginxuser;
#pid /home/nginxuser/nginx.pid;
worker_processes auto;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    # Load the real IP module
    set_real_ip_from 172.17.0.1/32;  # Add any other trusted proxies as needed
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;    

    # Configure rate limiting
    limit_req_zone $remote_addr zone=addr:50m rate=2r/s;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    default_type application/octet-stream;

    gzip on;
    gzip_disable "msie6";

    include /etc/nginx/conf.d/*.conf;

    # Modify log format to use $remote_addr
    log_format main '$remote_addr | $time_local | $status | $server_port | $request | $http_user_agent';

    # Setup logging
    error_log /etc/nginx/logs/error.log warn;
    access_log /etc/nginx/logs/access.log main;
    access_log /dev/stdout main;


    types {
        text/html html htm shtml;
        text/css css;
        application/javascript js;
        application/json json;
        application/xml xml;
        text/xml xml;
        image/png png;
        image/jpeg jpeg jpg;
        image/gif gif;
        image/svg+xml svg svgz;
        application/octet-stream bin exe;
        application/pdf pdf;
        application/zip zip;
        audio/mpeg mp3;
        video/mp4 mp4;
        video/webm webm;
        video/ogg ogv;
        application/x-shockwave-flash swf;
    }

}
