name: Publisher

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  push:
    branches:
      - 'latest'
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Cleanup deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: Code

      - name: Clone DiceRoller repository into Code/dice
        run: |
          git clone --depth=1 https://github.com/TeamCorgo/DiceRoller.git Code/dice
        env:
          GIT_TERMINAL_PROMPT: 0  # Prevents prompts for authentication

      - name: Clone SpaceMailRoom repository into Code/mail
        run: |
          git clone --depth=1 https://github.com/TeamCorgo/SpaceMailRoom.git Code/mail
        env:
          GIT_TERMINAL_PROMPT: 0  # Prevents prompts for authentication

      - name: Clone Instruments repository into Code/instruments
        run: |
          git clone --depth=1 https://github.com/TeamCorgo/Instruments.git Code/instruments
        env:
          GIT_TERMINAL_PROMPT: 0  # Prevents prompts for authentication

      - name: Clone Image2Mega repository into Code/image2mega
        run: |
          git clone --depth=1 https://github.com/TeamCorgo/Image2Mega.git Code/image2mega
        env:
          GIT_TERMINAL_PROMPT: 0  # Prevents prompts for authentication

      # Upload generated files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Code

  deploy:
    needs: build  # Ensure deploy runs after build completes
    permissions:
      pages: write  # Grant permission to write to GitHub Pages
      id-token: write  # Grant permission for id-token usage
    environment:
      name: github-pages  # Environment name for deployment
      url: ${{ steps.deployment.outputs.page_url }}  # URL of deployed pages
    runs-on: ubuntu-latest
    steps:
      # Deploy generated Doxygen files to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4